### ISSUE TITLE
Add explicit support for variants

### ISSUE THREAD

**Issue by kerrmarin** [design-ops/stylable-swiftui#1]
Consider the scenario where a button can have two different states: enabled and disabled. It would be nice to be able to style the button with a single identifier and set the variant one way or another. Pseudocode to illustrate:

```
struct MyButton: View {
    @State private var isEnabled = true
    var body: some View {
        Button(action: {
            self.isEnabled = !self.isEnabled
        }) {
            Text("Button")
        }.style("buttonIdentifier", variant: self.isEnabled ? "enabled" : "disabled")
    }
}
```
And then in the stylist you would have something like...
```
stylist.addStyle(identifier: "buttonIdentifier[enabled]") {
    // Style for enabled state
}
```

**Comment by deanWombourne** [comment]
Oh, I thought that already worked :| Though, with the current system the style set for `buttonIdentifier[enabled]` _won't_ inherit from `buttonIdentifier` - you would have to explicitly set everything.

**Comment by deanWombourne** [comment]
OK, looking more deeply at the code, I think the interface on `Stylistidentifier` for variants could do with some work - currently it only really works with strings i.e. `StylistIdentifier("section/element[variant]/atom")` will work as expected.

However, your pseudocode doesn't hit some edge cases, like specifying which component in the identifier will have the variant applied to it i.e. in the case of `.style("section/buttonIdentifier/atom", variant: "Enabled")`. Sigh, it's tricky, and I'm tried from being on lockdown with two kids :) Any suggestions?

**Comment by kerrmarin** [comment]
No suggestions so far but IMHO how identifiers are constructed should be "implementation detail" i.e. no need for user to know `[x]` is a variant. I might even go further and suggest identifiers should have properties of their own for sections, organisms, elements and atoms instead of just a string (ofc with some behind-the-scenes magic to make "section/organism/element/atom" also a valid identifier).

Another example where I would like to use variants would be a UI like this:

![vRKie](https://user-images.githubusercontent.com/2995710/78390420-71c1c280-75dc-11ea-98e7-19b38403b7ae.png)

Where the tokens for "Loan" i.e. the pink, green and yellow bits are all the same atom but in different variants. How the variants are set is completely arbitrary and doesn't have a pre-defined set of values (unlike perhaps enabled/disabled or `UIControl.State` values).

**Comment by kerrmarin** [comment]
Although I guess that's how it works atm where you can create a stylist identifier with any number of components 🤔

**Comment by deanWombourne** [comment]
So, @atomoil (and me!) were thinking that the number of components in an identifier was a decision for the user of the library (i.e. we used section/element/atom before, but then wanted to use section/component/element/atom later on) and the library shouldn't be opinionated about that.

The concession we made was to have a method which would extract a component at a specific index, so this extension would be trivial in a client app:

```swift
/// Assuming section/element/atom
extension StylistIdentifier {

    var section: String { component(at: 2) }
    var element: String { component(at: 1) }
    var atom: String { component(at: 0) }
}
```

However, looking at the code as-is now, we didn't actually finish that . . . . sigh. StylistIdentifier has an internal representation of a component (called . . . wait for it . . . . `Component`) which combines a value, and an optional variant, and we didn't want to expose that to the end user. However that might have been the wrong call.

When you ask for `myIdentifier.element` would you want to know the variant as well?

i.e. given the identifier;

```swift
let identifier: StylistIdentifier = "products/primaryButton[selected]/title"
```

what would `identifier.element` return? Either "primaryButton", or some struct containing "primaryButton" and "selected"?

**Comment by deanWombourne** [comment]
(FYI: It's a trivial change to make `StylistIdentifier.Component` public, and make the already existing method `component(at:)` public as well. However, you know my view on making too much public . . . . ;)

**Comment by deanWombourne** [comment]
Also, the library has absolutely no opinion on what a variant is - it's all strings behind the scenes. That's a hard requirement as an identifier has to map to / from a string literal.

**Comment by kerrmarin** [comment]
Was thinking about this last night and I think what annoys me is having to construct the string for a variant as a consumer of this library. e.g. in my example above I'd have to do something like...
```
struct MyButton: View {
    @State private var isEnabled = true
    var body: some View {
        Button(action: {
            self.isEnabled = !self.isEnabled
        }) {
            Text("Button")
        }.style("buttonIdentifier[\(self.isEnabled ? "enabled" : "disabled")]")
    }
}
```
I think it would be a nicer API if the library abstracts away how variants are encoded into the identifier string 🤔 
maybe i'm making more of a fuss than it's worth...

**Comment by kerrmarin** [comment]
> When you ask for myIdentifier.element would you want to know the variant as well?

Yes, I think `myIdentifier.element` would return a `Component` but I do agree with the n-components as opposed to having them named. It's trivial for a user of this library to have an extension of identifier to "name" each component according to how it's called in that team.

Another question.. kinda related... 

`StylistIdentifier` is what we use to find a style for each component i.e. a StylistIdentifier is `x/y/z/atom[state]` but when we nominate a component for styling we use a `StylistIdentifier` when in reality what we create is more like a `Component`? in the example above:

```
.style("buttonIdentifier[\(self.isEnabled ? "enabled" : "disabled")]")
```
but how likely/encouraged is it to style components with a string like:
```
.style("organism/element/buttonIdentifier")
```

**Comment by kerrmarin** [comment]
Just realised your first comment pretty much says what I mentioned in these two last comments 🤦‍♂

**Comment by atomoil** [comment]
I _presume_ `StyleIdentifier("section/buttonIdentifier/atom", variant: "enabled")` would apply the variant to all of the components. I don't know if `"section/buttonIdentifier/atom".applying(variant: "enabled")` would also be possible or not. PRs welcome ;-)

I guess `"section/buttonIdentifier/atom".applying(variant: "enabled", at: 2)` would be a way of adding a variant to just one component (presuming just `applying(variant:)` is possible.

So far I've thought that using a string (eg `.style("organism/element/buttonIdentifier")`) would be the preferred way of doing things. @kerrmarin if it wasn't - how would you prefer it to work?

Actually, one of the biggest challenges for me to make this super awesome is how to handle designer to developer handoff - if you have any thoughts on that I'd be super grateful.

One thing that occurs to me (massive tangent warning, but might inform any exposure of `Component`) is that variants are actually used in a couple of different ways, as discussed in this article  https://www.cjcid.com/articles/ions-introduction/ - this makes me wonder whether `organism/element[state:disabled;colorscheme:dark]/atom` could be a thing in some future version, with just `organism/element[disabled]/atom` meaning `element`'s '`state`' (aka default) variant is `disabled`.

**Comment by atomoil** [comment]
one other thought - conversations to this point have been that atoms wouldn't have variants, but now I think about it I'm not sure why. @cdemetriadis do you have any thoughts on this?

**Comment by cdemetriadis** [comment]
Atoms must be unique. Atoms can change depending on their context only.




--
Constantinos Demetriadis
Digital Designer
ohmylovely.com

**Comment by atomoil** [comment]
What's the reasoning behind atoms having to be unique?

**Comment by deanWombourne** [comment]
ideally, we would want to be able to use either a String, a Component or a Stylistidentifier when we call `style(_:)`.

We would also want a dsl to create variants of components i.e. `Component("button").variant("selected")` We'd also probably want helper methods on String to do `"button".variant("selected")`

i.e. These should all work.

```swift
style("button/title")
style("button[selected]/title")
style(Component("button"))
style(Component("button").variant("selected"))
style("button".variant("selected"))
```

FYI There's already a dsl for combining identifiers - you can do this.

```swift
let sectionIdentifier = StylistIdentifier("section")
let completeIdentifier = "button/title".within(sectionIdentifier)
```

We should also extend this to work for Components as well.

i.e.

```swift
let sectionIdentifier = StylistIdentifier("section")
let component = Component("button").variant("selected")
let completeIdentifier = "title".within(component).within(sectionIdentifier)
```

And, imho, while _we_ don't want atoms to have variants, it's actually harder to prevent that than it is just to let them have the option variants and just not use that functionality :)

**Comment by cdemetriadis** [comment]
If the last statement is the case, sure. Let atoms have variants and we just don’t tell anyone ;)

The idea behind atoms is that they ARE unique in the the sense that we only have one title, one subtitle, one background etc. you can name them anyway you like, but you should use variants on the element or organism to change the atoms within. If that’s not the case then things get very confusing. Like, why should I use title instead if title[caps] and so forth. They lose context.


--
Constantinos Demetriadis
Digital Designer
ohmylovely.com

**Comment by deanWombourne** [comment]
@kerrmarin I'm poking the code, and I've probably missed something, but is your whole problem fixed with this extension on String?

```swift
extension String {

    public func withVariant(_ variant: String?) -> StylistIdentifier {
        let component = StylistIdentifier.Component(value: self, state: variant)
        return StylistIdentifier(components: [component])
    }
}
```

with no need to make Component public at all?

This would allow things like:

```"atom".within("primaryButton".withVariant("selected"))```

which would remove your horrendous ternary.

**Comment by kerrmarin** [comment]
I... guess? Although I'm not a huge fan of "polluting" the String API like that. It also leaves open the edge case of

```
"organism/section".withVariant("selected") // what does this return?
```

I'll have better formed opinions on how I feel about using the library in the next month or so as I style more and more components :)

**Comment by deanWombourne** [comment]
Yep, that's exactly the kind of reason why I shouldn't do that :) I'm trying to see if we can do this without making Component public, but I don't think there is anymore.

**Comment by deanWombourne** [comment]
OK, the only way I can see to do this is to only allow Component when previously we have allowed full StylistIdentifiers i.e. this would no longer be allowed: 

```swift
StylistGroup("component/element") {
    Text().style("title")
}
```

it would have to be replaced with this:

```swift
StylistGroup("component") {
  StylistGroup("element") {
    Text().style("title")
  }
}
```

Then, adding variants is a trivial second parameter to the `StylistGroup` methods i.e.

```swift
StylistGroup("element", variant: "selected") {
```

I wouldn't add this extra parameter to the `style` function, as we don't want to allow atoms to be given variants, and I've assumed that if you are calling `style` you're at the atom level. Though, there's nothing we can do to stop people just passing in an atom with a variant explicitly!

However, this is a breaking change - @kerrmarin you seem to be using this library most, would this affect anything you have written so far?

**Comment by atomoil** [comment]
I would expect `"section/organism".withVariant("selected")` to return `section[selected]/ organism[selected]`

Personally I think it's nice we have the string functionality we have at the moment as it makes implementing very lightweight (at the cost of not being compiler safe)

Instead of breaking up StylistGroup, would a method like this be possible:
```
StylistGroup(StylistIdentifier("element", variant: "selected").within(StylistIdentifier("component")) {
    Text().style("title")
}
```

or even (for readability):
```StylistGroup(StylistIdentifier("component").containing(StylistIdentifier("element", variant: "selected"))```

Perhaps compiler safety could be a function of the generating step (eg if it generated an enum that is `CustomStringConvertible`)

`.style(self.isEnabled ? .buttonIdentifierEnabled : .buttonIdentifierDisabled)`

**Comment by deanWombourne** [comment]
I can't see a use case for setting the variant at every point in a stylist identifier to the same value at the same call, so I strongly vote we don't add `.withVariant()` to StylistIdentifier.

Unfortunately, that makes your next idea harder (though not impossible).

We need to make StylistGroup accept either a StylistIdentifier, or a Component (or a String) - once we can do that then all these are possible.

```swift
StylistGroup("component/element")
StylistGroup("element".within("component"))
StylistGroup(Component("element", variant: "selected").within("component"))
```

(and, adding the `containing` vs. `within` method is trivial - one just calls the other swapping the arguments around :)

**Comment by deanWombourne** [comment]
Though, do we agree that `.style("atom")` should only ever accept a `Component`, and never a full `StylistIdentifier`?

**Comment by deanWombourne** [comment]
Also, again trivial, we could do operator overloading things like this:

```swift
StylistIdentifier("component") + StylistIdentifier("element", variant: "selected")
```

which, with the string literal magic, could look like this:

```swift
StylistIdentifier("component") + "element"
```

**Comment by atomoil** [comment]
> Though, do we agree that `.style("atom")` should only ever accept a `Component`, and never a full `StylistIdentifier`?

I'm not sure 😬 

Perhaps it's a good idea to look at this from a distance and define how we think say a control which has states, would work with the Stylist. 

So, given the example in this thread of a button called `MyButton` which has `enabled` and `disabled` states - how should that ideally be constructed with `.style()` and `StylistGroup`s ?

**Comment by deanWombourne** [comment]
But in UIKit a Button isn't an atom - the button's text would be the atom? i.e. the variant would be like `button[selected]/title` - so .style("title") wouldn't care about state.

Though, I think @kerrmarin is using this library in anger so he's probably the best placed to help here!

**Comment by kerrmarin** [comment]
I'm closing this, it's been 4 months since any activity and I haven't encountered this problem since.
