### ISSUE TITLE
String case in `Text` items

### ISSUE THREAD

**Issue by kerrmarin** [design-ops/stylable-swiftui#10]
We don't have the ability at the moment to control whether a `Text` view should show uppercase or lowercase. It would be a nice addition to the library to be able to do that.

Things I've tried:
- Custom modifier
- Extension on `Text` to apply uppercase or not

Perhaps one way to solve this may need to be to have a custom `Text` view?

**Comment by kerrmarin** [comment]
I should say neither of the things I tried I was able to get working... A naïve implementation of this would be something like:
```
struct CaseableText: View {

    let contents: String

    init(_ contents: String) {
        self.contents = contents
    }

    var body: some View {
        Text(self.contents)
    }
}

extension CaseableText {
    func uppercased() -> CaseableText {
        CaseableText(self.contents.uppercased())
    }
}
```

Then in the stylist we use a similar approach to `styleText`..

**Comment by kerrmarin** [comment]
OK so a couple of updates on this:

- iOS 14 has a `textCase(_:)` function: https://developer.apple.com/documentation/swiftui/text/textcase(_:). It only supports uppercase and lowercase. Perhaps we could use that and only support it on iOS 14 and above?
- I found another way to do it by using `Text`'s formatter initializer: https://developer.apple.com/documentation/swiftui/text/init(_:formatter:)-1v7mr. Basically create a formatter for uppercase/lowercase/titlecase and extend Text with a new initializer:

```
public extension Text {
    init<Content: ReferenceConvertible>(_ content: Content, formatterIdentifier: StylistIdentifier) {
        let formatter = UppercaseStringFormatter() // TODO: get the right formatter based on the formatterIdentifier
        self.init(content, formatter: formatter)
    }
}
```

Any thoughts on approach @deanWombourne @atomoil @cdemetriadis ?

**Comment by deanWombourne** [comment]
My immediate thought (probably without enough research) would be option 2 - it allows us to cover all the cases we want. Option 1 might not be extended to include the other string formats Sketch can export.

**Comment by atomoil** [comment]
I prefer the 2nd option too, as we aren’t limited to Apple’s out of the box formatters

**Comment by deanWombourne** [comment]
We're still screwed by not being able to get to the string inside a Text instance (there might not actually be one until it's rendered!) so Option 2 still requires us to use a special Text init method, instead of just being able to style a Text the same way we style everything else :| This means the users would have to remember to _always_ use our special init, just in case a new style formats some text. Sigh.

**Comment by kerrmarin** [comment]
So my main issue with number 2 is that it would mean all text styling happens through the initializer instead of via the standard `style(_:)` method. This has the problem that we can no longer use the convenience initializers for `Text` (e.g. localisation support, formatting support). We could add the localisation support by including an initializer for that but we would definitely lose the ability to use https://developer.apple.com/documentation/swiftui/text/init(_:formatter:)-1v7mr.

There is already a precedent for something similar (`StylableImage`) so perhaps instead of an extension to Text we should have a `StylableText`? This wouldn't fix the formatter initializer issue.

Current way of styling text:
```
Text("Hello, world!").style("body")
```
Potential new ways:
```
Text("Hello, world!", styleIdentifier: "body")
StylableText("Hello, world!", styleIdentifier: "body")
```

To accomplish this in the convertor we would have to have a way of matching different case formatters to the ones we want (e.g. a lookup of identifier -> Optional<Formatter>)

**Comment by kerrmarin** [comment]
Option 1 doesn't have this limitationm, you would use the regular text initializer. It obvs only works on iOS 14, and is limited to uppercase/lowercase/nothing but conveniently that's also the only casing supported in Sketch.

**Comment by deanWombourne** [comment]
_oh_ I didn't realise it matched what Sketch supports . . . . I think I might be changing my opinion :( I assume we'd just fall back to not styling in iOS <14?

**Comment by kerrmarin** [comment]
Yeah, iOS 13 just wouldn't have any casing styles, but retain all other styling

**Comment by kerrmarin** [comment]
Was fixed in https://github.com/design-ops/sketch-to-swiftUI/pull/29
