### ISSUE TITLE
Add "verbose" mode

### ISSUE THREAD

**Issue by kerrmarin** [design-ops/stylable-swiftui#11]
Currently, this library prints out when it's applying any styles to any views. I suggest we add a verbose flag to enable and disable these prints to the console.

**Comment by deanWombourne** [comment]
+1

(+2 if you add verbosity levels ;)

**Comment by kerrmarin** [comment]
Fixed by 154366f66c00fc6cf0cd6ee1ea98fe2c3dc4546d
