### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by kerrmarin** [design-ops/stylable-swiftui#15]
I guess v2 since we removed a public extension on `String`?

**Comment by deanWombourne** [comment]
If we haven't hit 1.x yet then all bets are off. If we've released 1 then yes this sadly has to be 2. Don't know where to check on the mobile site, sorry!

**Comment by kerrmarin** [comment]
Yep, it would be v2. I can make all the changes to the code and then I'll ping you and you make the pod release?

**Comment by deanWombourne** [comment]
Sounds good to me

**Comment by kerrmarin** [comment]
Code and tag pushed to origin 👍

**Comment by deanWombourne** [comment]
Hah, only just got round to this (sorry!) and it turns out I’m not an owner of the pod :) You need to poke atomoil - and we should probably both get added as owners while he’s in there.

S

**Comment by atomoil** [comment]
cool, will add it to my todo list and get onto it _soon_

**Comment by atomoil** [comment]
2.0 is pushed to trunk. Overjoyed to add you both as owners, please dm me your pod trunk username and I'll see to it (`pod trunk me` will show you your current sessions) or see https://guides.cocoapods.org/making/getting-setup-with-trunk.html with instructions for creating one.

**Comment by deanWombourne** [comment]
It’s, predictably, deanWombourne (or deanWombourne@gmail.com <mailto:deanWombourne@gmail.com> if it insists on an email).

S
