### ISSUE TITLE
--radius modifier matching pattern

### ISSUE THREAD

**Issue by cdemetriadis** [design-ops/stylable-swiftui#17]
Currently, the `--radius` modifier only matches the identical styles. 

For example: `tag/background --radius` will be applied only to the `tag/background` layer style.

If I create `carouselSmall/tag/background --radius` it will be ignored unless I create a `carouselSmall/tag/background` layer style as well.

Ideally, modifiers would behave as any other atom in the system. I should be able to create overrides for specific radii without the need to create a style for it.

**Comment by kerrmarin** [comment]
This should be addressed in the convertor: https://github.com/design-ops/sketch-to-swiftUI/issues/19
