### ISSUE TITLE
Add ability to get UIImage from stylist identifier

### ISSUE THREAD

**Issue by kerrmarin** [design-ops/stylable-swiftui#24]
It's useful when having to use UIKit components to be able to access the underlying UIImage.

**Comment by deanWombourne** [comment]
I'm about to rewrite the image loading stuff to fit NDS - I can add a method to UIImage which will take an identifier and return the matching image from the asset bundle. It's 99% the same code when trying to find the correct image from the name anyway :)

**Comment by kerrmarin** [comment]
Awesome. I gave it a shot earlier but was a bit flabbergasted with the whole identifier inheritance etc. Be good to see how you do it!

**Comment by deanWombourne** [comment]
Autoclose from github, but my PR was just part of the fix for this :) Reopening.

**Comment by kerrmarin** [comment]
Fixed by #24
