### ISSUE TITLE
Applying variants to `View`

### ISSUE THREAD

**Issue by kerrmarin** [design-ops/stylable-swiftui#3]
I have the following view:

```
public struct TagView: View {
    public var body: some View {
       StylableGroup("tag") {
            VStack {
                Text("Some text").style("label")
            }.style("background")
        }
    }
}
```
This view is always going to be a "tag" view. What I'd like to do is then use this view anywhere I want to be able to set the variant for it like:
```
TagView().with(variant: "variant")
```
which would then make the view have identifiers like `*/*/tag[variant]/label` and `*/*/tag[variant]/background`. If I didn't call `with(variant:)` then the TagView would just be `*/*/tag/label` and `*/*/tag/background`.

The current way to do this is not to have the StylableGroup in `TagView` and have each "TagView" as:
```
StylableGroup("tag[variant]") {
   TagView()
}
```
I think it would be a nice bit addition :)

**Comment by deanWombourne** [comment]
Would you want this to just be a method on _any_ `View`? 

And, would also want to grab the variant value from inside that view as well (i.e. a method `getVariant() -> String?` on `View`?

**Comment by deanWombourne** [comment]
Reading your example more closely, how would we know which component in the identifier to apply the variant to? I could probably get it to attach the variant to the first StylableGroup it finds, but this edge case would exist:

```swift
public var body: some View {
  VStack {
    StylableGroup("elementA") {
      VStack {
        Text("Some text").style("label")
      }.style("background")
    }
    StylableGroup("elementB") {
      VStack {
        Text("Some other text").style("label")
      }.style("background")
    }
  }
}
```

Assuming the identifier for the first background would be `elementA[variant]/background` after calling `.variant('variant")`, what would you expect the identifier to be for the second background? I guess the options are just `elementB/background` or `elementB[variant]/background`?

**Comment by kerrmarin** [comment]
@deanWombourne in the case you show I would expect it to apply the variant to all groups at the same level as the first one it finds so in that example: `elementB[variant]/background`

**Comment by kerrmarin** [comment]
IDK what I was thinking when I opened this
