### ISSUE TITLE
Extract Embedded Fonts

### ISSUE THREAD

**Issue by cdemetriadis** [design-ops/stylable-swiftui#35]
Now that Sketch supports embedded fonts we can extract those instead of looking for a match on the user's system - which is not always ~ideal~ a good idea.

Only caveat is that the file MUST have the fonts embedded - which is a good thing.

**Comment by kerrmarin** [comment]
This was fixed in the convertor https://github.com/design-ops/sketch-to-swiftUI/pull/38
