### ISSUE TITLE
View with atom only should have styles applied

### ISSUE THREAD

**Issue by kerrmarin** [design-ops/stylable-swiftui#6]
Basically this test should pass... I think?

```
    func testStylistMatches_thisShouldPass() throws {
        let stylist = Stylist()

        var didApplyGeneral = false
        var didApplySpecific = false
        stylist.addStyle(identifier: "*/*/element/atom") { view -> AnyView in
            didApplySpecific = true
            return AnyView(view.foregroundColor(.red))
        }

        stylist.addStyle(identifier: "*/organism/*/atom") { view -> AnyView in
            didApplyGeneral = true
            return AnyView(view.foregroundColor(.blue))
        }

        let stylable = Stylable(AnyView(Text("Test")), identifier: "atom")
        _ = stylist.style(view: stylable, identifier: "atom")

        XCTAssertFalse(didApplyGeneral)
        XCTAssertTrue(didApplySpecific)
    }
```

**Comment by deanWombourne** [comment]
Yes, yes it should - `"atom"` should be equivalent to `"*/*/*/atom"`.

I'll take a look.

**Comment by deanWombourne** [comment]
Wait - no it shouldn't match. "*/element/atom" is specific to atoms which are inside element. Just passing in "atom" by itself doesn't match that criteria.

@cdemetriadis or @atomoil might need a vote here :) And if I'm wrong, then we probably need to do some fairly large work on rewriting `StylistIdentifier`!

**Comment by kerrmarin** [comment]
Shouldn't write bugs with half a bottle of wine in me!

**Comment by atomoil** [comment]
@deanWombourne is correct `*/*/element/atom` is for atoms inside element.

With this system a developer should always be as specific as possible (to allow for overrides in specific places) and a designer should provide a general case eg `*/*/*/atom` in the design and then use overrides for specific cases (eg when in element as in the example)

**Comment by atomoil** [comment]
> Shouldn't write bugs with half a bottle of wine in me!

LOL. That’s usually how I introduce bugs 😬

**Comment by deanWombourne** [comment]
also, phew - didn't like to think about the implications of this!

also also, only half?

**Comment by cdemetriadis** [comment]
Correct, this should not pass.

**Comment by deanWombourne** [comment]
![giphy](https://user-images.githubusercontent.com/7887119/78975625-6276d380-7b0c-11ea-949c-748948cd6254.gif)
