### ISSUE TITLE
Stop polluting String's namespace

### ISSUE THREAD

**Issue by deanWombourne** [design-ops/stylable-swiftui#8]
There is a method (`within`) which operates directly on the `String` type. All this method does is wrap `StylistIdentifier.within`, i.e. these lines are equivalent and produce the same `StylistIdentifier`.

```swift
"title".within("button")
StylistIdentifier("title").within("button")
```

Should we allow this pollution on the String namespace, given that if we have added a single method it sets precedence for more to be added later?

Our options here are:

1. Yes, this is fine. We do nothing.
2. Remove the convenience method on `String` and decide we don't want to do that
3. Move the convenience method on `String` into a sub-pod so users can opt-in.

Thoughts?

**Comment by atomoil** [comment]
Sorry for being dumb, but I don't understand option 3 - can you elaborate?

Generally I'm ok with adding to the String's namespace, but only so long as we do it in moderation, and I acknowledge that adding anything sets future precedence to add more 😬

**Comment by deanWombourne** [comment]
3 would mean putting all the string extension into a sub-pod which isn't included by default - that way if users want to extend String they can opt-in, but by default String isn't touched.

I think autocorrect has replaced 'sub-pod' with 'subbed' :)

**Comment by atomoil** [comment]
LOL yes, I didn't understand subbed but I do understand sub-pod

**Comment by atomoil** [comment]
Personally I like option 1, but if it's at all contentious then I am also fine with option 3

**Comment by atomoil** [comment]
Seeing as we're blocking #7 why don't we go with option 3 and add it as a subpod - or is there something Im missing?

**Comment by kerrmarin** [comment]
IMHO the string methods don't really make sense i.e. if you're a new user of this library and you're reading code what does `"title".within("button")` do? is the string "title" in the string "button"? something else? it's not immediately obvious. This could be mitigated with different naming of the method 🤔 

If we add `contains` or `containing` to string, what does that method do? in swift `contains` on string already exists so IMHO it could lead to confusion when using this library.

IMO the syntactic benefits of having these methods on `String` don't outweigh the readability detriments and cognitive load additions of adding them to the `String` API.

**Comment by kerrmarin** [comment]
☝️  doesn't mean that I support a hard-and-fast rule to never add to the String API just that I don't think inthis situation it's right :)

**Comment by deanWombourne** [comment]
The more I see it written, the more I think I should never have written it.

**Comment by kerrmarin** [comment]
I think in this case it would be useful to point out that I see a `StylistIdentifier` as something that can be _initialized_ with a `String` but not something that is _interchangeable_ for a `String` if that makes sense?

**Comment by deanWombourne** [comment]
I assume we're not looking at removing the string literal stuff, just the extra methods on String?

**Comment by kerrmarin** [comment]
IMO yes

**Comment by atomoil** [comment]
Actually.... I've changed my mind... I think `within` or `containing` should only operate on `StylistIdentifier` and not directly on `String` - and we should still allow the string literal initialisation stuff.

**Comment by deanWombourne** [comment]
Holy Shit - we have quorum! I'll remove those methods from master, and from my PR.

**Comment by deanWombourne** [comment]
Done and Done.
